# permissions for end users to view failoverconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: failoverconfig-viewer-role
rules:
- apiGroups:
  - failover.open-cluster-management.io
  resources:
  - failoverconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - failover.open-cluster-management.io
  resources:
  - failoverconfigs/status
  verbs:
  - get
